### ISSUE TITLE
Autotest and minitest-server are not working on Windows

### ISSUE THREAD

**Issue by IanTrudel** [seattlerb/minitest-server#1]
minitest (default: 5.4.1)
minitest-autotest (1.0.3)
minitest-reporters (1.1.14)
minitest-server (1.0.4)

Running autotest command line on jruby 9.1.8, Windows 10:
```
Unhandled exception: UNIXServer is required
E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/drb/unix.rb:6:in `<main>'
  org/jruby/RubyKernel.java:961:in `require'
  E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `(root)'
  E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in `require'
  E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/drb/drb.rb:846:in `auto_load'
  E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/drb/drb.rb:814:in `open_server'
  E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/drb/drb.rb:1446:in `initialize'
  E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/drb/drb.rb:1736:in `start_service'
  E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/gems/shared/gems/minitest-server-1.0.4/lib/minitest/server.rb:15:in `run'
  E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/gems/shared/gems/minitest-autotest-1.0.3/lib/autotest.rb:237:in `run'
  E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/gems/shared/gems/minitest-autotest-1.0.3/lib/autotest.rb:137:in `<main>'
  org/jruby/RubyKernel.java:979:in `load'
  E:\Programmes\Ruby\jruby-9.1.8.0\bin\autotest:24:in `<main>'
Quitting
```
Adding the following patch to .autotest:
```ruby
class Minitest::Server
  def self.path pid = $$
    "druby://localhost:6541"
  end
end
```
It partially fix the problem but not quite yet:
```
E:\Programmes\Ruby\jruby-9.1.8.0\bin\jruby -I.;lib;test -rubygems -e "gem 'minitest'; %w[minitest/autorun test/test_simple_number.rb].each { |f| require f }" -- --server 19924
LoadError: UNIXServer is required
                       <main> at E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/drb/unix.rb:6
                      require at org/jruby/RubyKernel.java:961
                       (root) at E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
                      require at E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
                    auto_load at E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/drb/drb.rb:846
                   uri_option at E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/drb/drb.rb:837
                   initialize at E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/drb/drb.rb:1140
                 new_with_uri at E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/drb/drb.rb:1120
                   initialize at E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/gems/shared/gems/minitest-server-1.0.4/lib/minitest/server_plugin.rb:23
  block in plugin_server_init at E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/gems/shared/gems/minitest-server-1.0.4/lib/minitest/server_plugin.rb:15
                         each at org/jruby/RubyArray.java:1734
                 init_plugins at E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/minitest.rb:73
                 init_plugins at E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/minitest.rb:71
                 block in run at E:/Programmes/Ruby/jruby-9.1.8.0/lib/ruby/stdlib/minitest.rb:122
```

**Comment by zenspider** [comment]
I don't have (or want to have) windows so I'm not going to be able to provide or test a fix for this.

Switching wholesale to a socket is not preferable tho. UNIXSocket is cleaner/better when it is available.

**Comment by zenspider** [comment]
No response. Should I close this or wait for someone to step up?

**Comment by zenspider** [comment]
No response. Closing.
